FROM python:3.7.8
RUN apt-get update
COPY . /umbra
WORKDIR /umbra
ENV PYTHONPATH "${PYTHONPATH}:/umbra"
RUN python setup.py install
# TODO: how to pass this address:port arg?
EXPOSE 8910
CMD python ./umbra/agent/umbra-agent --uuid agent --address 172.17.0.2:8910 --debug
