FROM python:3.7.8
RUN apt-get update && apt install -y net-tools iproute2 inetutils-ping iperf3 && apt clean
COPY . /umbra
WORKDIR /umbra
ENV PYTHONPATH "${PYTHONPATH}:/umbra"
ENV AGENT_ADDR "172.17.0.1"
ENV AGENT_PORT "8910"
RUN python setup.py install
# TODO: how to pass this address:port arg?
#EXPOSE 8910
CMD python ./umbra/agent/umbra-agent --uuid agent --address ${AGENT_ADDR}:${AGENT_PORT} --debug
